-- Recruweb NOVA AI Interview feature
-- Run this once against the same DB used by the Job Portal backend.
CREATE TABLE IF NOT EXISTS ai_screening_interviews (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  candidate_id INT NULL,
  initiated_by_user_id INT NULL,
  hr_user_id INT NULL,
  job_id INT NULL,
  job_title VARCHAR(255) NULL,
  candidate_name VARCHAR(255) NULL,
  company_logo TEXT NULL,
  phase VARCHAR(32) NOT NULL DEFAULT 'core',
  phase_turns INT NOT NULL DEFAULT 0,
  turns INT NOT NULL DEFAULT 0,
  question_index INT NOT NULL DEFAULT 0,
  question_started_at DATETIME NULL,
  question_time_limit_seconds INT NOT NULL DEFAULT 60,
  timed_out_questions JSON NOT NULL,
  transcript JSON NOT NULL,
  question_plan JSON NOT NULL,
  asked_questions JSON NOT NULL,
  scores JSON NOT NULL,
  answer_evaluations JSON NOT NULL,
  avg_score DECIMAL(5,2) NULL,
  ai_recommendation VARCHAR(64) NULL,
  evaluation_summary JSON NULL,
  status ENUM('pending_approval','approved','in_progress','completed','terminated','rejected') NOT NULL DEFAULT 'pending_approval',
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  proctoring JSON NOT NULL,
  review_score DECIMAL(5,2) NULL,
  review_decision ENUM('PENDING','HIRE','HOLD','REJECT') NOT NULL DEFAULT 'PENDING',
  reviewed_by_user_id INT NULL,
  reviewed_at DATETIME NULL,
  video_recording_url VARCHAR(1000) NULL,
  video_mime_type VARCHAR(128) NULL,
  video_duration_seconds INT NULL,
  answer_videos JSON NOT NULL,
  hr_approval_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  admin_approval_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  hr_approved_by_user_id INT NULL,
  admin_approved_by_user_id INT NULL,
  hr_approved_at DATETIME NULL,
  admin_approved_at DATETIME NULL,
  approval_requested_at DATETIME NULL,
  approval_rejection_reason TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_nova_user (user_id),
  KEY idx_nova_candidate (candidate_id),
  KEY idx_nova_initiator (initiated_by_user_id),
   KEY idx_nova_hr (hr_user_id),
   KEY idx_nova_hr_approval (hr_approval_status),
   KEY idx_nova_admin_approval (admin_approval_status),
  KEY idx_nova_job (job_id),
  KEY idx_nova_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
