import React,{useEffect,useState} from "react";
import axios from "axios";
import { Settings2, ShieldCheck, ClipboardCheck, RefreshCw, Activity, CheckCircle2 } from "lucide-react";
import { ADMIN_API_ENDPOINT } from "../../utils/data";

const API=ADMIN_API_ENDPOINT;
const Card=({children,className=""})=><div className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 ${className}`}>{children}</div>;
export default function WorkforceControls({auditOnly=false}){
 const [permissions,setPermissions]=useState([]),[logs,setLogs]=useState([]),[overview,setOverview]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const calls=[axios.get(`${API}/workforce-controls`,{withCredentials:true}),axios.get(`${API}/workforce-audit`,{withCredentials:true}),axios.get(`${API}/workforce-oversight`,{withCredentials:true})];const [p,a,o]=await Promise.all(calls);setPermissions(p.data.permissions||[]);setLogs(a.data.logs||[]);setOverview(o.data.overview||null)}catch(e){setError(e?.response?.data?.message||"Admin workforce controls unavailable")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const toggle=async item=>{setBusy(item.key);try{await axios.put(`${API}/workforce-controls/${encodeURIComponent(item.key)}`,{enabled:!item.enabled},{withCredentials:true});setPermissions(x=>x.map(p=>p.key===item.key?{...p,enabled:!p.enabled}:p));}catch(e){setError(e?.response?.data?.message||"Permission update failed")}finally{setBusy("")}};
 if(loading)return <div className="min-h-screen bg-slate-50 p-8 dark:bg-slate-950"><div className="mx-auto max-w-6xl animate-pulse font-bold text-slate-500">Loading workforce controls…</div></div>;
 return <div className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950 md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-blue-600"><Settings2 className="h-4 w-4"/> Admin Control Plane</div><h1 className="mt-2 text-3xl font-black text-slate-950 dark:text-white">Global Workforce Governance</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Control access to advanced workforce modules and keep an auditable trail of administrator changes.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-4 py-2.5 text-sm font-black text-white"><RefreshCw className="h-4 w-4"/> Refresh</button></div>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={ShieldCheck} label="Pending verification" value={overview?.pendingVerification||0}/><Stat icon={CheckCircle2} label="Verified workers" value={overview?.verifiedWorkers||0}/><Stat icon={Activity} label="Active bulk requests" value={overview?.activeBulkRequests||0}/><Stat icon={ClipboardCheck} label="Activity / 24h" value={overview?.activity24h||0}/></div>
 {!auditOnly&&<Card className="mt-6"><div className="flex items-center justify-between"><div><h2 className="font-black text-slate-950 dark:text-white">Workforce permissions</h2><p className="mt-1 text-xs text-slate-500">Disabled modules should be hidden or blocked by the application layer.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black text-blue-700">{permissions.filter(x=>x.enabled).length}/{permissions.length} enabled</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{permissions.map(item=><div key={item.key} className="flex items-center justify-between rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div><p className="text-sm font-black">{item.label}</p><p className="mt-1 text-[10px] font-mono text-slate-400">{item.key}</p></div><button disabled={busy===item.key} onClick={()=>toggle(item)} className={`relative h-7 w-12 rounded-full transition ${item.enabled?"bg-emerald-500":"bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${item.enabled?"left-6":"left-1"}`}/></button></div>)}</div></Card>}
 <Card className="mt-6"><div className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-blue-500"/><h2 className="font-black text-slate-950 dark:text-white">Admin audit trail</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b text-slate-500"><th className="p-3">Time</th><th className="p-3">Admin</th><th className="p-3">Action</th><th className="p-3">Target</th><th className="p-3">Details</th></tr></thead><tbody>{logs.map(l=><tr key={l.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3 whitespace-nowrap">{new Date(l.created_at).toLocaleString()}</td><td className="p-3 font-bold">{l.adminName||"Admin"}</td><td className="p-3 font-bold">{l.action}</td><td className="p-3">{l.target_id||"—"}</td><td className="p-3 max-w-sm truncate">{l.details||"—"}</td></tr>)}{!logs.length&&<tr><td colSpan="5" className="p-6 text-center text-slate-500">No audit events yet.</td></tr>}</tbody></table></div></Card>
 </div></div>;
}
function Stat({icon:Icon,label,value}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><Icon className="h-5 w-5 text-blue-500"/><p className="mt-3 text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{Number(value).toLocaleString()}</p></div>}
